= Spring Security OAuth 2.0
:toc: right

== Запуск и настройка Keycloak

.Команда запуска Keycloak в Docker
[source,shell]
----
docker run --name keycloak -p 8080:8080 \
-e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin \
-v ./config/keycloak:/opt/keycloak/data/import \
quay.io/keycloak/keycloak:23.0.6 \
start-dev --import-realm
----

.Использованные флаги
|===
|Флаг |Назначение

|`--name`
|Название контейнера

|`-p 8080:8080`
|Проброс порта 8080 из контейнера на порт 18080 хост-системы

|`-e`
|Переменные окружения KEYCLOAK_ADMIN и KEYCLOAK_ADMIN_PASSWORD

|`-v ./config/keycloak:/opt/keycloak/data/import`
|Проброс директории `config/keycloak` проекта в директорию `/opt/keycloak/data/import` контейнера для импорта и экспорта настроек пространства
|===

После старта будет создан realm sandbox с пользователем j.dewar и паролем password.

== Структура проекта

Проект состоит из двух основных компонентов:

*Клиент-сервис*: +
- Представлен сервисом oidc-client +
- Этот сервис является клиентом взаимодействия с ресурс-сервисом. +
- Инициирует процесс аутентификации пользователя через сервер авторизации (Keycloak). +
- Получает уникальный код подтверждения от сервера авторизации для обмена на токен доступа. +
- Использует полученный токен доступа для доступа к ресурс-сервису.

*Ресурс-сервис*: +
- Представлен сервисом greetings-resource-service +
- Этот сервис предоставляет защищенные ресурсы. +
- Требует от клиент-сервиса предоставить действительный токен доступа для доступа к ресурсам.