spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/sandbox
            user-name-attribute: preferred_username
        registration:
          greetings-app-client-credentials:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: greetings-app
            client-secret: 8PjJFWHfYuZUQVDJvhdpsfrRrjBa0lhK
            scope:
              - greetings
          greetings-app-authorization-code:
            provider: keycloak
            client-id: greetings-app
            client-secret: 8PjJFWHfYuZUQVDJvhdpsfrRrjBa0lhK
            scope:
              - openid
              - microprofile-jwt

server:
  port: 8079

